### ISSUE TITLE
TSError: ⨯ Unable to compile TypeScript:

### ISSUE THREAD

**Issue by flavum-kashif** [Treblle/treblle-express#5]
Using Trebble in typeScript project lead to error- 
Error- ure- Error- src/app.ts:6:21 - error TS7016: Could not find a declaration file for module ‘@treblle/express’. ‘backend/node_modules/@treblle/express/index.js’ implicitly has an ‘any’ type.
Try npm i --save-dev @types/treblle__express if it exists or add a new declaration (.d.ts) file containing declare module '@treblle/express';

6 import treblle from “@treblle/express”
~~~~~~~~~~~~~~~~~~

at createTSError (backend\node_modules\ts-node\src\index.ts:859:12)
at reportTSError (backend\node_modules\ts-node\src\index.ts:863:19)
at getOutput (backend\node_modules\ts-node\src\index.ts:1077:36)
at Object.compile (backend\node_modules\ts-node\src\index.ts:1433:41)
at Module.m._compile (backend\node_modules\ts-node\src\index.ts:1617:30)
at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
at Object.require.extensions.<computed> [as .ts] (backend\node_modules\ts-node\src\index.ts:1621:12)       
at Module.load (node:internal/modules/cjs/loader:1207:32)
at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
at Module.require (node:internal/modules/cjs/loader:1235:19) {
diagnosticCodes: [ 7016 ]

**Comment by cindreta** [comment]
Hey there @flavum-kashif thx for submitting the detilsz @nikme Is going to take a look at it shortly and report back.

**Comment by nikme** [comment]
hi @flavum-kashif, I have added typescript types with example, and published a new version.
p.s. I have added some breaking changes, the new variable for blocked req path is called _blocklistPaths_ now.
